healthblock/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('api/', include('api_services.urls'))
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path('', views.index, name="index"),
    path('staff', views.staffs_view, name="staffs"),
    path('departments', views.departments_view, name="departments"),
    path('departments/<int:id>', views.department_view, name="department"),
    path('staff/<int:id>', views.delete_staff_view, name="delete"),
    path('staff/create', views.staff_view, name="staff"),
    path('successful/<str:data>', views.success_view, name="success"),
    path('accounts/login/', views.login_view, name="login"),
    path('accounts/register', views.register_view, name="register"),
    path('accounts/logout', views.logout_view, name="logout")
]

main/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class User(AbstractUser):
    pass

class Event(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="user_events")
    description = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"User: {self.user.username} | Action: {self.description}"

    def serialize(self):
        return {
            "staff": f"{self.user.first_name} {self.user.last_name}",
            "action": self.description,
            "date": self.created_at.strftime("%b %d %Y %H:%M:%S")
        }

class Departmet(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

class Staff(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="staff_details")
    department = models.ForeignKey(Departmet, on_delete=models.CASCADE, related_name="staff_department")
    job = models.CharField(max_length=255)
    phone = models.CharField(max_length=255)
    address = models.CharField(max_length=255)
    is_doctor = models.BooleanField(default=False)
    is_it = models.BooleanField(default=False)
    is_receptionist = models.BooleanField(default=False)
    is_lab = models.BooleanField(default=False)
    is_analyst = models.BooleanField(default=False)
    is_director = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name}"
    
class Patient(models.Model):
    first_name = models.CharField(max_length=255, default='')
    last_name = models.CharField(max_length=255, default='')
    age = models.CharField(max_length=255, default='')
    address = models.CharField(max_length=255, default='')
    telephone = models.CharField(max_length=255, default='')
    next_of_kin_first_name = models.CharField(max_length=255, default='')
    next_of_kin_last_name = models.CharField(max_length=255, default='')
    next_of_kin_address = models.CharField(max_length=255, default='')
    next_of_kin_telephone = models.CharField(max_length=255, default='')
    next_of_kin_relationship = models.CharField(max_length=255, default='')
    status = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Medical_History_Classes(models.Model):
    name = models.CharField(max_length=255, default='')

    def __str__(self):
        return self.name

class Past_Medical_History(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name="patient_medical_history")
    classification  = models.ForeignKey(Medical_History_Classes, on_delete=models.CASCADE, related_name="medical_history_classification")
    description = models.CharField(max_length=255)

    def __str__(self):
        return f"{self.patient.first_name}\'s medical history"

    def serialize(self):
        return {
            "patient": self.patient.id,
            "classification": self.classification.name,
            "description": self.description
        }

class Family_And_Social_History_Classes(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Family_And_Social_History(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name="patient_family_and_social_history")
    classification  = models.ForeignKey(Family_And_Social_History_Classes, on_delete=models.CASCADE, related_name="family_and_social_history_classification")
    description = models.CharField(max_length=255)

    def serialize(self):
        return {
            "patient": self.patient.id,
            "classification": self.classification.name,
            "description": self.description
        }


    def __str__(self):
        return f"{self.patient.first_name}\'s social and family history"

class Appointment(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name="patient_appointment")
    doctor = models.ForeignKey(Staff, on_delete=models.CASCADE, related_name="doctor_appointments")
    is_active = models.BooleanField(default=True)
    date = models.DateTimeField(auto_now=True)

class Patient_Monitor(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name="patient_monitor")
    staff = models.ForeignKey(User, on_delete=models.CASCADE, related_name="doctor_action_on_patient")
    description = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now=True)

    def serialize(self):
        return {
            "staff": self.staff.first_name,
            "patient": self.patient.first_name,
            "description": self.description,
            "date": self.date.strftime("%b %d %Y %H:%M:%S")
        }

    def __str__(self):
        return f"{self.patient} activity"

class Investigation_Request(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name="patient_investigation_request")
    staff = models.ForeignKey(User, on_delete=models.CASCADE, related_name="doctor_investigation_request_on_patient")
    description = models.CharField(max_length=255)
    is_active = models.BooleanField(default=True)
    is_paid = models.BooleanField(default=False)
    date = models.DateTimeField(auto_now=True)

class Financial_Record(models.Model):
    investigation = models.ForeignKey(Investigation_Request, on_delete=models.CASCADE, related_name="item_paid_for")
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE, related_name="patient_payment")
    amount_paid = models.CharField(max_length=255)
    date = models.DateTimeField(auto_now=True)

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.urls import reverse
from .models import User, Staff, Patient, Event, Departmet
from rest_framework.authtoken.models import Token
from django.db import IntegrityError
import json
import ast
from .utils import create_event

# Create your views here.
@login_required
def index(request):

    loggedin_user = request.user

    if loggedin_user.is_staff or loggedin_user.is_superuser or loggedin_user.staff_details.get().is_it or loggedin_user.staff_details.get().is_director:
        create_event(request.user, "Loggedin to IT staff portal")
        pass
    else:
        create_event(request.user, "Tried to access IT staff portal")
        messages.error(request, "You have no access!")
        return HttpResponseRedirect(reverse("main:logout"))

    event_count = Event.objects.filter(user=loggedin_user).count

    user_count = User.objects.all().count()
    staff_count = Staff.objects.all().count()
    doctor_count = Staff.objects.filter(is_doctor=True).count()
    patient_count = Patient.objects.all().count()
    staff_name = f"{loggedin_user.first_name} {loggedin_user.last_name}"
    staff_username = loggedin_user.username
    staff_number = loggedin_user.id
    staff_email = loggedin_user.email

    try:
        staff = Staff.objects.get(user=loggedin_user)

        staff_job = staff.job
        staff_department = staff.department.name
        staff_phone = staff.phone
        staff_address = staff.address

        context = {
            "user_count": user_count,
            "staff_count": staff_count,
            "doctor_count": doctor_count,
            "patient_count": patient_count,
            "staff_username": staff_username,
            "staff_name": staff_name,
            "staff_number": staff_number,
            "staff_phone": staff_phone,
            "staff_email": staff_email,
            "staff_job": staff_job,
            "staff_department": staff_department,
            "staff_event_count": event_count,
            "staff_address": staff_address
        }

    except Staff.DoesNotExist:
        
        context = {
            "user_count": user_count,
            "staff_count": staff_count,
            "doctor_count": doctor_count,
            "patient_count": patient_count,
            "staff_username": staff_username,
            "staff_name":staff_name,
            "staff_number":staff_number,
            "staff_email": staff_email,
            "staff_event_count": event_count
        }

    # staff_phone: loggedin_user.phone
    # staff_job = loggedin_user.staff_details.get().job
    # staff_department = loggedin_user.staff_details.get().staff_department.get().name


    return render(request, 'main/index.html', context)

@login_required
def staffs_view(request):

    loggedin_user = request.user

    if loggedin_user.is_staff or loggedin_user.is_superuser or loggedin_user.staff_details.get().is_it or loggedin_user.staff_details.get().is_director:
        pass
    else:
        create_event(request.user, "Tried to access IT staff portal")
        messages.error(request, "You have no access!")
        return HttpResponseRedirect(reverse("main:logout"))

    if request.method == "GET":

        staffs = Staff.objects.all()

        staffs_info = []

        for staff in staffs:
            staff_job = staff.job
            staff_department = staff.department.name
            staff_phone = staff.phone
            staff_address = staff.address
            staff_username = staff.user.username
            staff_name = f"{staff.user.first_name} {staff.user.last_name}"
            staff_number = staff.user.id
            staff_email = staff.user.email
            event_count = Event.objects.filter(user=staff.user).count()


            staff_detail = {
                "staff_username": staff_username,
                "staff_name": staff_name,
                "staff_number": staff_number,
                "staff_phone": staff_phone,
                "staff_email": staff_email,
                "staff_job": staff_job,
                "staff_department": staff_department,
                "staff_event_count": event_count,
                "staff_address": staff_address
            }

            staffs_info.append(staff_detail)

        create_event(request.user, "Accessed staffs page")
        return render(request, "main/staffs.html", {"staffs": staffs_info})

@login_required
def staff_view(request):

    loggedin_user = request.user

    if loggedin_user.is_staff or loggedin_user.is_superuser or loggedin_user.staff_details.get().is_it or loggedin_user.staff_details.get().is_director:
        pass
    else:
        create_event(request.user, "Tried to access IT staff portal")
        messages.error(request, "You have no access!")
        return HttpResponseRedirect(reverse("main:logout"))

    if request.method == "POST":

        first_name = request.POST['first-name']
        last_name = request.POST['last-name']
        username = request.POST['username']
        address = request.POST['address']
        job = request.POST['job']
        department = request.POST['department']
        phone = request.POST['phone']
        email = request.POST['email']
        password = request.POST['password']
        is_doctor = request.POST.get('is-doctor')
        is_it = request.POST.get('is-it')
        is_receptionist = request.POST.get('is-receptionist')
        is_analyst = request.POST.get('is-analyst')
        is_lab = request.POST.get('is-lab')
        is_director = request.POST.get('is-director')

        if first_name is "" or last_name is "" or username is "" or address is "" or job is "" or department is "" or phone is "" or email is "" or password is "":
            messages.error(request, "Fields can't be empty!")
            create_event(request.user, "Tried to register a new staff from staff portal")
            return HttpResponseRedirect(reverse("main:staff"))

        if is_doctor is None and is_it is None and is_receptionist is None and is_analyst is None and is_lab is None and is_director:
            messages.error(request, "Staffs must have atleast one privilege")
            create_event(request.user, "Tried to register a new staff from staff portal")
            return HttpResponseRedirect(reverse("main:staff")) 

        try:
            new_user = User.objects.create_user(
                username = username,
                password = password,
                email = email,
                first_name = first_name,
                last_name = last_name,
            )
            new_user.save()
            token = Token.objects.create(user=new_user)
        except:
            create_event(request.user, "Tried to register a new staff from staff portal")
            messages.error(request, "Unable to create a user")
            return HttpResponseRedirect(reverse("main:staff"))

        try:
            new_staff = Staff(
                user = new_user,
                department = Departmet.objects.get(pk=int(department)),
                job = job,
                phone = phone,
                address = address,
                is_doctor = True if is_doctor is not None else False,
                is_it = True if is_it is not None else False,
                is_receptionist = True if is_receptionist is not None else False,
                is_lab = True if is_lab is not None else False,
                is_analyst = True if is_analyst is not None else False,
                is_director = True if is_director is not None else False            
            )
            new_staff.save()
        except IntegrityError:
            create_event(request.user, "Tried to register a new staff from staff portal")
            messages.error(request, "Unable to create a new user")
            return HttpResponseRedirect(reverse("main:staff"))


        data = {
            "message":"User created successfully",
            "new_user": f"{new_staff.user.first_name} {new_staff.user.last_name}",
            "new_user_username": new_staff.user.username,
            "date": str(new_staff.user.date_joined )   
        }
        create_event(request.user, f"Registered a new staff | {new_staff.user.first_name} {new_staff.user.last_name}")
        return HttpResponseRedirect(reverse("main:success", args=(data,)))

    if request.method == "GET":

        departments = Departmet.objects.all()
        create_event(request.user, "Accessed staff creation page from IT staff portal")
        return render(request, "main/staff.html", {
            "departments": departments
        })

@login_required
def delete_staff_view(request, id):

    loggedin_user = request.user

    if loggedin_user.is_staff or loggedin_user.is_superuser or loggedin_user.staff_details.get().is_it or loggedin_user.staff_details.get().is_director:
        pass
    else:
        create_event(request.user, "Tried to access IT staff portal")
        messages.error(request, "You have no access!")
        return HttpResponseRedirect(reverse("main:logout"))

    if request.method == "GET":

        try:
            staff_to_delete = User.objects.get(pk=id)
        except User.DoesNotExist:
            messages.error(request, "User not found!")
            return HttpResponseRedirect(reverse("main:staffs"))

        create_event(request.user, f'Accessed staff deletion page for {staff_to_delete.first_name} {staff_to_delete.last_name}')

        return render(request, "main/delete.html", {
            "user_number": staff_to_delete.id,
            "user_to_delete": f'{staff_to_delete.first_name} {staff_to_delete.last_name}'
        })

    if request.method == "POST":
        
        val = request.POST['val']
        try:
            user_to_delete = User.objects.get(pk=val)

main/templates/main/delete.html
{% extends "main/layout.html" %}
{% load static %}

{% block body %}

<!-- Page-Title -->
<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <div class="page-title-box">
            <div class="row">
                <div class="col">
                    <h4 class="page-title"></h4>
                </div><!--end col-->  
            </div><!--end row-->                                   
        </div><!--end page-title-box-->
    </div><!--end col-->
    <div class="col-sm-2"></div>
</div><!--end row-->
<!-- end page title end breadcrumb -->


<div class="row">

    <div class="col-lg-3">
    </div>


    <div class="col-lg-6">
        
        <div class="" id="exampleModalDanger" tabindex="-1" role="dialog" aria-labelledby="exampleModalDanger1" aria-hidden="true">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header bg-danger">
                        <h6 class="modal-title m-0 text-white" id="exampleModalDanger1">Confirm staff deletion</h6>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div><!--end modal-header-->
                    <div class="modal-body">
                        <div class="row">
                            <div class="col-lg-3 text-center align-self-center">
                                <img src="{% static '/main/style/assets/images/widgets/btc.png' %}" alt="" class="img-fluid">
                            </div><!--end col-->
                            <div class="col-lg-9">
                                <h5>You are abbout to delete this user</h5>
                                <span class="badge bg-soft-secondary">Staff services will be disabled from</span>
                                <small class="text-muted ms-2">Deletion time</small>
                                <ul class="mt-3 mb-0">
                                    <li id="confirm-user">User Number: {{user_number}}</li>
                                    <li id="confirm-user-name">User: {{user_to_delete}}</li>
                                    <li>Deleting this staff will revoke all user access to the system. Are you sure you want to proceed?</li>
                                </ul>
                            </div><!--end col-->
                        </div><!--end row-->                                                     
                    </div><!--end modal-body-->
                    <div class="modal-footer"> 
                        <form action="{% url 'main:delete' user_number %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="val" value="{{user_number}}">
                            <button type="submit" id="confirm-delete" class="btn btn-soft-danger btn-sm" data-bs-dismiss="modal">Delete staff</button>
                        </form>                                                   
                        
                    </div><!--end modal-footer-->
                </div><!--end modal-content-->
            </div><!--end modal-dialog-->
        </div><!--end modal-->
              
    </div><!--end col-->


    <div class="col-lg-3">
        
    </div>

</div>

{% endblock %}

main/templates/main/departments.html
{% extends "main/layout.html" %}
{% load static %}

{% block body %}

<!-- Page-Title -->
<div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
        <div class="page-title-box">
            <div class="row">
                <div class="col">
                    <h4 class="page-title">Departments</h4>
                </div><!--end col-->  


            </div><!--end row-->                                   
        </div><!--end page-title-box-->


        <div class="card">
            <div class="card-header">
                <div class="row align-items-center">
                    <div class="col">                      
                        <h4 class="card-title">Create Department</h4>                      
                    </div><!--end col-->                                        
                </div>  <!--end row-->                                  
            </div><!--end card-header-->
            <div class="card-body">
                <div class="row">
                    <div class="col-lg-12">
                        <form action="{% url 'main:departments' %}" method="POST">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3 col-6 mb-2 mb-lg-0">
                                        
                                        <input type="text" name="title" class="form-control" id="pro-start-date" placeholder="Title">
                                    </div><!--end col-->  
                                    <div class="col-lg-6 col-6 mb-2 mb-lg-0">
                                        
                                        <input type="text" name="description" class="form-control" id="pro-start-date" placeholder="Description">
                                    </div><!--end col-->  
                                    <div class="col-lg-3 col-6 mb-2 mb-lg-0">
                                        <button type="submit" class="btn form-control btn-soft-primary ">Create department</button> 
                                    </div><!--end col-->   
                                                                                           
                                </div><!--end row-->
                            </div><!--end form-group-->
                            
                        </form>  <!--end form-->
                    </div><!--end col-->
                </div><!--end row-->                                                                              
            </div><!--end card-body-->
        </div><!--end card-->

    </div><!--end col-->
    <div class="col-sm-2"></div>
</div><!--end row-->
<!-- end page title end breadcrumb -->



<div class="row">
    <div class="col-lg-2">
    </div>
    <div class="col-lg-8">

        <hr>

        <div class="row">
            <div class="col-12">
                    <div class="card-body">
                        <button class="btn btn-soft-warning tippy-btn" id="myElement" data-tippy-interactive="true" data-tippy-theme="light rounded" data-tippy-arrow="true" data-tippy-size="large" data-tippy-arrowTransform="scale(2)" data-tippy-animation="fade" data-tippy-distance="15" data-tippy-interactiveBorder="20" data-local>View warning</button>
                        <div id="feature__html" data-template>
                            <div style="padding:20px"><img width="50" src="{% static '/main/style/assets/images/logo.png' %}" alt="" />
                                <h5>On clicking the button <strong>Delete</strong>, It will delete the department without any confirmation.</h5>
                            </div>
                        </div>
                    </div><!--end card-body-->
        </div> <!-- end row -->

        <hr>

        {% for department in departments %}
        <div class="card">
            <div class="card-header">
                <div class="row align-items-center">
                    <div class="col">                      
                        <h4 class="card-title">{{department.name}}</h4>                      
                    </div><!--end col-->

                    <div class="col-auto"> 
                            <a href="{% url 'main:department' department.id %}"><i class="las la-trash-alt text-danger font-20"></i></a>
                            
                    </div><!--end col-->    
                </div>  <!--end row-->    
            </div><!--end card-header-->
            <div class="card-body">
                <div class="row">
                        
                    <div class="col-lg-12 ms-auto align-self-center">
                        <ul class="list-unstyled personal-detail mb-0">
                            <li class=""><i class="ti ti-user me-2 text-secondary font-16 align-middle"></i> <b> Name </b> : {{department.name}}</li>
                            <li class="mt-2"><i class="ti ti-key text-secondary font-16 align-middle me-2"></i> <b> Description </b> : {{department.description}}</li>
                            <li class="mt-2"><i class="ti ti-key text-secondary font-16 align-middle me-2"></i> <b> Creation date </b> : {{department.created_at}}</li>                   
                        </ul>
                       
                    </div><!--end col-->
               
                </div><!--end row-->
            </div><!--end card-body--> 
        </div><!--end card--> 
        {% endfor %}
    </div><!--end col-->
    <div class="col-lg-2">
    </div>
</div><!--end row-->

{% endblock %}

main/templates/main/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    {% include 'main/partials/top_links.html' %}
</head>
<body>
    
    <!-- Left Sidenav -->
    <div class="left-sidenav">
        <!-- LOGO -->
        <div class="brand">
            <a href="{% url 'main:index' %}" class="logo">
                <span>
                    <img src="{% static '/main/style/assets/images/logo.png' %}" alt="logo-small" class="logo-sm">
                </span>
            </a>
        </div>
        <!--end logo-->
        <div class="menu-content h-100" data-simplebar>
            <ul class="metismenu left-sidenav-menu">
                <li class="menu-label mt-0">Main</li>

                <li class="nav-item"><a class="nav-link" href="{% url 'main:index' %}"><i class="ti-control-record"></i>Home</a></li>

                <li class="nav-item"><a class="nav-link" href="{% url 'main:departments' %}"><i class="ti-control-record"></i>Departments</a></li>

                <li class="nav-item"><a class="nav-link" href="{% url 'main:staffs' %}"><i class="ti-control-record"></i>Staffs</a></li>

             
                <hr class="hr-dashed hr-menu">

            </ul>

            <div class="update-msg text-center">
                <a href="javascript: void(0);" class="float-end close-btn text-muted" data-dismiss="update-msg" aria-label="Close" aria-hidden="true">
                    <i class="mdi mdi-close"></i>
                </a>
                <h5 class="mt-3">Health Block</h5>
                <p class="mb-3">Updates are coming soon</p>
                
            </div>
        </div>
    </div>
    <!-- end left-sidenav-->
    

    <div class="page-wrapper">
        <!-- Top Bar Start -->
        <div class="topbar">            
            <!-- Navbar -->
            <nav class="navbar-custom">    
                <ul class="list-unstyled topbar-nav float-end mb-0">  
                    <li class="dropdown hide-phone">
                        <a class="nav-link dropdown-toggle arrow-none waves-light waves-effect" data-bs-toggle="dropdown" href="#" role="button"
                            aria-haspopup="false" aria-expanded="false">
                            <i data-feather="search" class="topbar-icon"></i>
                        </a>
                        
                        <div class="dropdown-menu dropdown-menu-end dropdown-lg p-0">
                            <!-- Top Search Bar -->
                            <div class="app-search-topbar">
                                <form action="#" method="get">
                                    <input type="search" name="search" class="from-control top-search mb-0" placeholder="Type text...">
                                    <button type="submit"><i class="ti-search"></i></button>
                                </form>
                            </div>
                        </div>
                    </li>                      

                    <li class="dropdown">
                        <a class="nav-link dropdown-toggle waves-effect waves-light nav-user" data-bs-toggle="dropdown" href="#" role="button"
                            aria-haspopup="false" aria-expanded="false">
                            <span class="ms-1 nav-user-name hidden-sm">{{request.user}}</span>
                            <img src="assets/images/users/user-5.jpg" alt="profile-user" class="rounded-circle thumb-xs" />                                 
                        </a>
                        <div class="dropdown-menu dropdown-menu-end">
                            
                            <a class="dropdown-item" href="{% url 'main:logout' %}"><i data-feather="power" class="align-self-center icon-xs icon-dual me-1"></i> Logout</a>
                        </div>
                    </li>
                </ul><!--end topbar-nav-->
    
                <ul class="list-unstyled topbar-nav mb-0">                        
                    <li>
                        <button class="nav-link button-menu-mobile">
                            <i data-feather="menu" class="align-self-center topbar-icon"></i>
                        </button>
                    </li> 
                    <li class="creat-btn">
                        <div class="nav-link">
                            <a class=" btn btn-sm btn-soft-primary" href="{% url 'main:staff' %}" role="button"><i class="fas fa-plus me-2"></i>New Staff</a>
                        </div>                                
                    </li>                           
                </ul>
            </nav>
            <!-- end navbar-->
        </div>
        <!-- Top Bar End -->

        <!-- Page Content-->
        <div class="page-content">
            <div class="container-fluid">
                {% include 'main/partials/messages.html' %}

                {% block body %}
                {% endblock %}


            </div><!-- container -->

            <footer class="footer text-center text-sm-start">
                &copy; <script>
                    document.write(new Date().getFullYear())
                </script> Health Block
            </footer><!--end footer-->
        </div>
        <!-- end page content -->
    </div>
    <!-- end page-wrapper -->
    
        {% include 'main/partials/bottom_links.html' %}

</body>
</html>